/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2018-06-24 16:32:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ddetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<link href=\"css/amazeui.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link href=\"css/admin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<link href=\"css/demo.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<link href=\"css/hmstyle.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t\t<link href=\"css/skin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/amazeui.min.js\"></script>\r\n");
      out.write("<title>我的订单</title>\r\n");
      out.write("<style> \r\n");
      out.write("        .black_overlay{ \r\n");
      out.write("            display: none; \r\n");
      out.write("            position: absolute; \r\n");
      out.write("            top: 0%; \r\n");
      out.write("            left: 0%; \r\n");
      out.write("            width: 100%; \r\n");
      out.write("            height: 100%; \r\n");
      out.write("            background-color: black; \r\n");
      out.write("            z-index:1001; \r\n");
      out.write("            -moz-opacity: 0.8; \r\n");
      out.write("            opacity:.80; \r\n");
      out.write("            filter: alpha(opacity=88); \r\n");
      out.write("        } \r\n");
      out.write("        .white_content { \r\n");
      out.write("            display: none; \r\n");
      out.write("            position: absolute; \r\n");
      out.write("            top: 25%; \r\n");
      out.write("            left: 25%; \r\n");
      out.write("            width: 55%; \r\n");
      out.write("            height: auto; \r\n");
      out.write("            padding: 20px; \r\n");
      out.write("            border: 10px solid orange; \r\n");
      out.write("            background-color: white; \r\n");
      out.write("            z-index:1002; \r\n");
      out.write("            overflow: auto; \r\n");
      out.write("        } \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:#F8F8F8;min-width:1500px;\">\r\n");
      out.write("\t\t<!--顶部导航条1 -->\r\n");
      out.write("\t\t<div name=\"导航1\" style=\"width:auto;margin: 0 auto;background-color: #333;margin-top: 0px;margin-right: auto;margin-bottom: 0px;margin-left: auto;height: 32px;line-height: 32px;min-width:1500px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-l\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage\" style=\"color:#ddd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-logo\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t欢迎使用网上订餐网站！\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-r\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage login\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd login\" ><span id = \"username\" target=\"_top\" style=\"color:#ddd\"> </span></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t|\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage register\" style=\"color:#ddd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd register\"><a onclick = \"loginout()\" target=\"_top\" style=\"color:#ddd\">注销</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage home\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd\"><a href=\"#\" target=\"_top\" style=\"color:#ddd\">开店申请</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage my-shangcheng\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd MyShangcheng\"><a href=\"my.jsp\" target=\"_top\" style=\"color:#ddd\"><i class=\"am-icon-user am-icon-fw\"></i>个人中心</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage mini-cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd\"><a id=\"mc-menu-hd\" href=\"#\" target=\"_top\" style=\"color:#ddd\"><i class=\"am-icon-shopping-cart  am-icon-fw\"></i><span>购物车</span><strong id=\"J_MiniCartNum\" class=\"h\">0</strong></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage favorite\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd\"><a href=\"#\" target=\"_top\" style=\"color:#ddd\"><i class=\"am-icon-heart am-icon-fw\"></i><span>收藏夹</span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--顶部导航条2-->\r\n");
      out.write("\t\t<div name=\"导航2\" style=\"height:130px;width:auto;background:white\">\r\n");
      out.write("\t\t\t\t\t<!-- icon -->\r\n");
      out.write("\t\t\t\t\t<div style=\"margin:0px 0px 0px 0px;;vertical-align:middle; height:100px;width:300px;float:left\">\r\n");
      out.write("\t\t\t\t\t\t<div  style=\"height:80px;width:180px;float:left \">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"image/logo.JPG\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div   style=\"font-size:25px;margin-top:50px;font-weight:600;height:80px;vertical-align:middle; width:100px; float:left \">\r\n");
      out.write("\t\t\t\t\t\t\t 网上订餐\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--悬浮搜索框-->\r\n");
      out.write("\t\t\t\t\t<div style=\"float: right;  margin-top:40px;width: 290px;height: 38px; border: 1px solid #e5e5e5;\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"searchInput\" style=\"    float: left;display: block;width: 225px;height: 38px; ;font-size: 14px;color: #535353;border: none;background: none;margin-left:5px \" name=\"index_none_header_sysc\" type=\"text\" placeholder=\"搜索商家，美食\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"ai-topsearch\" class=\"submit am-btn\" style=\"height:38px;width:100px float: left \" value=\"搜索\" index=\"1\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 导航条2.1 -->\r\n");
      out.write("\t\t\t\t\t<div style=\"text-align:center; margin-left:auto; margin-right:auto; margin-top:5px;text-align:center;vertical-align:middle; height:100px;width:740px\">\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"home.jsp\" style=\"float:left;margin:40px;font-size:30px\">首页</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\"float:left;margin:40px;font-size:30px\">我的订单</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"dp_register.jsp\" style=\"float:left;margin:40px;font-size:30px\">入驻加盟</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\"float:left;margin:40px;font-size:30px\">社会责任</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"clear \"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<!-- 支付页面具体内容 -->\r\n");
      out.write("\t\t<div style=\" width:1200px;margin-bottom:20px;  height:1200px;   color: #444444; margin-top: 20px;margin-right: auto;margin-bottom: 0px;margin-left: auto\">\r\n");
      out.write("\t\t\t<!-- 左边导航框 -->\r\n");
      out.write("\t\t\t<div style=\"background-color:white; float:left;width:300px;height:1000px\">\r\n");
      out.write("\t\t\t\t<!-- 近三个月的订单 -->\r\n");
      out.write("\t\t\t\t<div class=\"dd\" style=\"margin-top:50px;font-size:30px;height:80px;border-bottom:1px solid #ebebeb\">\r\n");
      out.write("\t\t\t\t\t<a class=\"ddbtn\"><img src=\"image/dh2.JPG\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t<div class=\"zh\" style=\"margin-top:20px;font-size:30px;height:80px;border-bottom:1px solid #ebebeb\">\r\n");
      out.write("\t\t\t\t\t<a class=\"zhbtn\"><img src=\"image/zhanghao2.JPG\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t <!-- 弹出框 -->\r\n");
      out.write("       \t\t\t <div id=\"light\" class=\"white_content\" >\r\n");
      out.write("       \t\t\t \t<a style=\"width:100%;font-size:25px;text-align:right;float:right; margin :5px;color:#ebebeb\" href=\"javascript:void(0)\" onclick=\"document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none';location.reload();\">关闭</a>\r\n");
      out.write("       \t\t\t \t<div style=\"height:100px;  width:780px;font-size:30px;text-align:center; margin :10px\">\r\n");
      out.write("       \t\t\t \t评论\r\n");
      out.write("       \t\t\t \t</div> \r\n");
      out.write("\t\t\t\t\t<div  style=\" text-align:center; margin :10px\">\r\n");
      out.write("\t\t\t\t\t\t<table style=\"margin-left:auto;margin-right:auto;   \">\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\" font-size:25px; margin :10px\">\r\n");
      out.write("\t\t\t\t\t\t选择评论等级：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"am-btn am-btn-danger\" onclick = \"status(3,this)\" style=\" font-size:20px; margin:10px\" >好评</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"am-btn am-btn-danger\" onclick = \"status(2,this)\" style=\" font-size:20px; margin:10px; \">中评</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"am-btn am-btn-danger\" onclick = \"status(1,this)\" style=\" font-size:20px; margin:10px \">差评</a>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tip\" style=\"display:none\"> 未选</div>\r\n");
      out.write("\t\t\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\"  id =\"commentstatus\"  >\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id =\"commentid\"  >\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id =\"commenton\"  >\r\n");
      out.write("\t\t\t\t\t\t</form>\t\r\n");
      out.write("\t\t\t\t\t\t<td style=\" font-size:25px; margin :10px\">\r\n");
      out.write("\t\t\t\t\t\t评论内容：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input id = \"commentcontent\" name=\"content\" style=\" font-size:25px; margin :10px\" type=\"text\" placeholder=\"输入评论内容\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" style=\"height:100px;margin :20px\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"am-btn am-btn-danger\" onclick=\"commit()\" style=\" font-size:25px; \" >确认</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"fade\" class=\"black_overlay\"></div> \r\n");
      out.write("\t\t\t<!--  内容框 -->\r\n");
      out.write("\t\t\t<div style=\"margin-left:10px;background-color:white; float:left;width:880px;min-height:1000px\" id = \"orderlist\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 脚注 -->\r\n");
      out.write("\t\t<div class=\"footer \" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-hd \" >\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \"> </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"home.jsp\">商城首页</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">支付宝</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">物流</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-bd \" >\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">关于我们</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">合作伙伴</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">联系我们</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">网站地图</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<script>\r\n");
      out.write("\t\t$(\".zhbtn\").click(function(){\r\n");
      out.write("\t\t\twindow.location.href=\"/OrderTakeOutFood/my.jsp\";\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script typr=\"text/javascript\">\r\n");
      out.write("var userorder = []\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("DisplayUsername();\r\n");
      out.write("$.ajax({\r\n");
      out.write("\turl:\"/OrderTakeOutFood/CustomerDisplayOrderServlet\",\r\n");
      out.write("\ttype:'get',\r\n");
      out.write("\tdatatype:'json',\r\n");
      out.write("\tsuccess:function(res){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar list = res.data.orderList;\r\n");
      out.write("\t\tconsole.log(res.data);\r\n");
      out.write("\t\tfor(i = 0;i<list.length;i++){\r\n");
      out.write("\t\t\t$(\"#orderlist\").append( '<div class=\"order\" style=\"border: 1px dashed #e5e5e5;width:auto;height:250px \">\t'\r\n");
      out.write("\t\t\t\t+'<div style=\"margin:10px; height:225px;width:300px;float:left\">'\r\n");
      out.write("\t\t\t\t+'<img src=\"/OrderTakeOutFood' + list[i].storePicture +'\">'\r\n");
      out.write("\t\t\t+'</div>'\r\n");
      out.write("\t\t\t+'<div style=\"margin:20px;width:515px;float:left;vertical-align:middle;height:210px\">'\r\n");
      out.write("\t\t\t+'<div style=\"text-align:left;  font-size:20px \">'\r\n");
      out.write("\t\t\t+'<div style=\"font-size: 20px;\">店家名字：' + list[i].storename + '</div>'\r\n");
      out.write("\t\t\t+'<div style=\"font-size: 20px;\">订单状况：'+ DisplayOrderStatus(list[i].orderStatus) +'</div>'\r\n");
      out.write("\t\t\t+'<div style=\"font-size: 20px;\">订单金额：¥' + list[i].sumprice +'元</div><div style=\"font-size: 20px;\">订单日期：' + timestampToTime(list[i].ordertime.time)\r\n");
      out.write("\t\t\t+'</div></div>'\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t+'<div style=\" float:right\">'\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t+'<a id=\"com_a'+i+'\" class=\"am-btn am-btn-danger\" href=\"javascript:void(0)\"  onclick=\"document.getElementById(\\'commentid\\').value='+list[i].storeid+';document.getElementById(\\'commenton\\').value='+list[i].orderNumber+';document.getElementById(\\'light\\').style.display=\\'block\\';document.getElementById(\\'fade\\').style.display=\\'block\\'\" style=\"font-size:15px;font-weight: bold;  font-family:黑体\"> 评论</a>'\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t+'</div>\t'\r\n");
      out.write("\t\t\t+'</div>'\r\n");
      out.write("\t\t+'</div>')\r\n");
      out.write("\t\tconsole.log(list.orderStatus)\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(list[i].orderStatus==0||list[i].orderStatus==1){\r\n");
      out.write("\t\t\t//alert(list[i].orderStatus)\r\n");
      out.write("\t\t\t$(\"#com_a\"+i+\"\").hide();\r\n");
      out.write("\t\t}else if(list[i].orderStatus==2){\r\n");
      out.write("\t\t\t//alert(list[i].orderStatus)\r\n");
      out.write("\t\t\t$(\"#com_a\"+i+\"\").show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//userorder[i]=list[i].storeid\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("function getNowFormatDate() {\r\n");
      out.write("    var date = new Date();\r\n");
      out.write("    var seperator1 = \"-\";\r\n");
      out.write("    var seperator2 = \":\";\r\n");
      out.write("    var month = date.getMonth() + 1;\r\n");
      out.write("    var strDate = date.getDate();\r\n");
      out.write("    if (month >= 1 && month <= 9) {\r\n");
      out.write("        month = \"0\" + month;\r\n");
      out.write("    }\r\n");
      out.write("    if (strDate >= 0 && strDate <= 9) {\r\n");
      out.write("        strDate = \"0\" + strDate;\r\n");
      out.write("    }\r\n");
      out.write("    var currentdate = date.getFullYear() + seperator1 + month + seperator1 + strDate\r\n");
      out.write("            + \" \" + date.getHours() + seperator2 + date.getMinutes()\r\n");
      out.write("            + seperator2 + date.getSeconds();\r\n");
      out.write("    return currentdate;\r\n");
      out.write("}\r\n");
      out.write("function commit(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar time = getNowFormatDate();\r\n");
      out.write("\t\r\n");
      out.write("\tvar comment = {\r\n");
      out.write("\t\t\tcommentcontent : $(\"#commentcontent\").val(),\r\n");
      out.write("\t\t\tpublishtime : time,\r\n");
      out.write("\t\t\tcommentstatus : $(\"#commentstatus\").val(),\r\n");
      out.write("\t\t\tstoreid : $(\"#commentid\").val(),\r\n");
      out.write("\t\t\tordernumber : $(\"#commenton\").val()\r\n");
      out.write("\t}\r\n");
      out.write("\t//alert($(\"#commentcontent\").val());\r\n");
      out.write("\t//alert($(\"#commentstatus\").val());\r\n");
      out.write("\t//alert($(\"#commentid\").val());\r\n");
      out.write("\t//alert($(\"#commenton\").val());\r\n");
      out.write("\t//alert(time);\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\tdatatype:\"json\",\r\n");
      out.write("\t\turl:\"/OrderTakeOutFood/CustomerAddCommentServlet\",\r\n");
      out.write("\t\tdata:comment,\r\n");
      out.write("\t\tsuccess:function(res){\r\n");
      out.write("\t\t\tif(res.code == 200)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\talert(res.message)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\talert(\"评论失败\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(){\r\n");
      out.write("\t\t\talert(\"失败\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function status(i,obj){\r\n");
      out.write("\t $(\"#commentstatus\").val(i)\r\n");
      out.write("\t $(\"#tip\").attr(\"style\",\"display:block;\")\r\n");
      out.write("\t// alert($(obj).html());\r\n");
      out.write("\t $(\"#tip\").html(\"已选\"+$(obj).html());\r\n");
      out.write("}\r\n");
      out.write("function timestampToTime(timestamp) {\r\n");
      out.write("    var date = new Date(timestamp);//时间戳为10位需*1000，时间戳为13位的话不需乘1000\r\n");
      out.write("    Y = date.getFullYear() + '-';\r\n");
      out.write("    M = (date.getMonth()+1 < 10 ? '0'+(date.getMonth()+1) : date.getMonth()+1) + '-';\r\n");
      out.write("    D = date.getDate() + ' ';\r\n");
      out.write("    h = date.getHours() + ':';\r\n");
      out.write("    m = date.getMinutes() + ':';\r\n");
      out.write("    s = date.getSeconds();\r\n");
      out.write("    return Y+M+D+h+m+s;\r\n");
      out.write("};\r\n");
      out.write("function DisplayOrderStatus(status){\r\n");
      out.write("\tif(status == 1)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\treturn \"已接单\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\telse if(status == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\treturn \"未接单\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\telse if(status == 2)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\treturn \"已完成\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\telse if(status ==3)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\treturn \"异常\";\r\n");
      out.write("\t\t}\r\n");
      out.write("};\r\n");
      out.write("function DisplayUsername(){\r\n");
      out.write("\t\tvar userJsonStr = sessionStorage.getItem('user');\r\n");
      out.write("\t\tuserEntity = JSON.parse(userJsonStr);\r\n");
      out.write("\t\tvar username = userEntity.username ;\r\n");
      out.write("\t\t$(\"#username\").html(username);\r\n");
      out.write("};\r\n");
      out.write("function loginout(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\turl:\"CustomerLoginOutServlet\",\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tdatatype:\"json\",\r\n");
      out.write("\t\tsuccess: function (data)  \r\n");
      out.write("        {  \r\n");
      out.write("      \t\r\n");
      out.write("     \t   if(data.code == 200)\r\n");
      out.write("     \t   {\r\n");
      out.write("     \t\t  sessionStorage.removeItem('user');\r\n");
      out.write("     \t\t$(location).attr('href', '/OrderTakeOutFood/login.jsp');\r\n");
      out.write("     \t   \talert(data.message)\r\n");
      out.write("     \t   \t\t\r\n");
      out.write("     \t   }else{\r\n");
      out.write("     \t\t   alert(data.message);\r\n");
      out.write("     \t   }\t\t   \t            \t\r\n");
      out.write("          },\r\n");
      out.write("        error: function()\r\n");
      out.write("        {\r\n");
      out.write("      \t  console.log(\"提交错误\")\r\n");
      out.write("        }\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("</script>\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
