/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2018-06-24 16:25:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dp_005fmy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<link href=\"css/amazeui.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link href=\"css/admin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<link href=\"css/demo.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<link href=\"css/hmstyle.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t\t<link href=\"css/skin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/amazeui.min.js\"></script>\r\n");
      out.write("<title>店铺个人中心</title>\r\n");
      out.write("<style> \r\n");
      out.write("        .black_overlay{ \r\n");
      out.write("            display: none; \r\n");
      out.write("            position: absolute; \r\n");
      out.write("            top: 0%; \r\n");
      out.write("            left: 0%; \r\n");
      out.write("            width: 100%; \r\n");
      out.write("            height: 100%; \r\n");
      out.write("            background-color: black; \r\n");
      out.write("            z-index:1001; \r\n");
      out.write("            -moz-opacity: 0.8; \r\n");
      out.write("            opacity:.80; \r\n");
      out.write("            filter: alpha(opacity=88); \r\n");
      out.write("        } \r\n");
      out.write("        .white_content { \r\n");
      out.write("            display: none; \r\n");
      out.write("            position: absolute; \r\n");
      out.write("            top: 25%; \r\n");
      out.write("            left: 25%; \r\n");
      out.write("            width: 55%; \r\n");
      out.write("            height: auto; \r\n");
      out.write("            padding: 20px; \r\n");
      out.write("            border: 10px solid orange; \r\n");
      out.write("            background-color: white; \r\n");
      out.write("            z-index:1002; \r\n");
      out.write("            overflow: auto; \r\n");
      out.write("        } \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:#F8F8F8;min-width:1500px;\">\r\n");
      out.write("\t\t<!--顶部导航条1 -->\r\n");
      out.write("\t\t<div name=\"导航1\" style=\"width:auto;margin: 0 auto;background-color: #333;margin-top: 0px;margin-right: auto;margin-bottom: 0px;margin-left: auto;height: 32px;line-height: 32px;min-width:1500px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-l\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage\" style=\"color:#ddd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-logo\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t欢迎使用网上订餐网站！\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-r\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage login\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd login\" ><a id=\"storename\" target=\"_top\" style=\"color:#ddd\"></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage login\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd login\" ><a    target=\"_top\" style=\"color:#ddd\" onclick=\"out()\">退出登陆 </a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--顶部导航条2-->\r\n");
      out.write("\t\t<div name=\"导航2\" style=\"height:130px;width:auto;background:white\">\r\n");
      out.write("\t\t\t\t\t<!-- icon -->\r\n");
      out.write("\t\t\t\t\t<div style=\"margin:0px 0px 0px 0px;;vertical-align:middle; height:100px;width:300px;float:left\">\r\n");
      out.write("\t\t\t\t\t\t<div  style=\"height:80px;width:180px;float:left \">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"image/logo.JPG\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div   style=\"font-size:25px;margin-top:50px;font-weight:600;height:80px;vertical-align:middle; width:100px; float:left \">\r\n");
      out.write("\t\t\t\t\t\t\t 网上订餐\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 导航条2.1 -->\r\n");
      out.write("\t\t\t\t\t<div style=\"text-align:center; margin-left:auto; margin-right:auto; margin-top:5px;text-align:center;vertical-align:middle; height:100px;width:740px\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\" #\" style=\" margin:40px;font-size:60px;font-weight:600 ;vertical-align:middle\">店铺管理界面</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"clear \"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<!-- 支付页面具体内容 -->\r\n");
      out.write("\t\t<div style=\" width:1200px;margin-bottom:20px;  height:1200px;   color: #444444; margin-top: 20px;margin-right: auto;margin-bottom: 0px;margin-left: auto\">\r\n");
      out.write("\t\t\t<!-- 左边导航框 -->\r\n");
      out.write("\t\t\t<div style=\"background-color:white; float:left;width:300px;height:1000px\">\r\n");
      out.write("\t\t\t\t<!-- 我的账号 -->\r\n");
      out.write("\t\t\t\t<div class=\"dd\" style=\"margin-top:50px;font-size:30px;height:80px; \">\r\n");
      out.write("\t\t\t\t\t<a href=\"dp_food.jsp\" style=\" margin-top:20px;font-size:25px;\">商品管理</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t<div class=\"zh\" style=\"margin-top:20px;font-size:30px;height:80px; \">\r\n");
      out.write("\t\t\t\t\t<a href=\"dp_order.jsp\"  style=\" margin-top:20px;font-size:25px;\">订单管理</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"zh\" style=\"background-color:#ebebeb; margin-top:20px;height:80px;border-bottom: 2px solid #F03726;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\"  style=\"color: #E4393C;font-weight:600; margin-top:20px;font-size:25px;\">店铺信息管理</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <!-- 弹出框 -->\r\n");
      out.write("       \t\t\t <div id=\"light\" class=\"white_content\" >\r\n");
      out.write("       \t\t\t \t<a style=\"width:100%;font-size:25px;text-align:right;float:right; margin :5px;color:#ebebeb\" href=\"javascript:void(0)\" onclick=\"document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none';location.reload();\">关闭</a>\r\n");
      out.write("       \t\t\t \t<div style=\"font-weight:600;height:100px;  width:780px;font-size:30px;text-align:center; margin :10px\">\r\n");
      out.write("       \t\t\t \t修改信息\r\n");
      out.write("       \t\t\t \t</div> \r\n");
      out.write("\t\t\t\t\t<div  style=\" text-align:center; margin :10px\">\r\n");
      out.write("\t\t\t\t\t<form id=\"alertform\">\r\n");
      out.write("\t\t\t\t\t\t<table style=\"margin-left:auto;margin-right:auto;   \">\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\" font-size:25px; margin :10px\">\r\n");
      out.write("\t\t\t\t\t\t配送金额：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"sendingfee\" style=\" font-size:25px; margin :10px\" type=\"text\" placeholder=\"输入修改内容\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\" font-size:25px; margin :10px\">\r\n");
      out.write("\t\t\t\t\t\t起送金额：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"deliverycost\" style=\" font-size:25px; margin :10px\" type=\"text\" placeholder=\"输入修改内容\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\" font-size:25px; margin :10px\">\r\n");
      out.write("\t\t\t\t\t\t店铺是否营业：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\" font-size:25px; margin :10px;text-align:left\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"storestatus\" style=\" font-size:25px; margin :10px\" type=\"text\" placeholder=\"输入修改内容\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\" font-size:25px; margin :10px\">\r\n");
      out.write("\t\t\t\t\t\t店铺电话：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\" font-size:25px; margin :10px;text-align:left\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"storetel\" style=\" font-size:25px; margin :10px\" type=\"text\" placeholder=\"输入修改内容\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\" font-size:25px; margin :10px\">\r\n");
      out.write("\t\t\t\t\t\t店铺图片：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\" font-size:25px; margin :10px;text-align:left\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"height:auto;width:300px;border: 1px dashed #e5e5e5;\">\r\n");
      out.write("               \t\t\t\t\t 图片上传前预览：<input   type=\"file\" id=\"xdaTanFileImg\" onchange=\"xmTanUploadImg(this)\" accept=\"image/*\"/>\r\n");
      out.write("           \t\t\t\t\t\t \r\n");
      out.write("           \t\t\t\t\t\t <img id=\"xmTanImg\"/>\r\n");
      out.write("           \t\t\t\t\t\t <div id=\"xmTanDiv\"></div>\r\n");
      out.write("       \t\t\t\t\t\t\t \r\n");
      out.write("      \t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" style=\"height:100px;margin :20px\">\r\n");
      out.write("\t\t\t\t\t\t<a id=\"alertsure\" class=\"am-btn am-btn-danger\" style=\" font-size:25px;margin-top:20px \">确认</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"fade\" class=\"black_overlay\"></div>\r\n");
      out.write("\t\t\t<!--  内容框 -->\r\n");
      out.write("\t\t\t<div id=\"infoform\" style=\"margin-left:10px;background-color:white; float:left;width:880px;height:1200px\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 脚注 -->\r\n");
      out.write("\t\t<div class=\"footer \" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-hd \" >\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \"> </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"home.jsp\">商城首页</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">支付宝</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">物流</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-bd \" >\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">关于我们</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">合作伙伴</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">联系我们</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">网站地图</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tDisplayStorername();\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"/OrderTakeOutFood/StoreDisplayInfoServlet\",\r\n");
      out.write("\t\ttype:'get',\r\n");
      out.write("\t\tdatatype:'json',\r\n");
      out.write("\t\tsuccess:function(res){\r\n");
      out.write("\t\t\tvar list = res.data.store;\r\n");
      out.write("\t\t\tconsole.log(res.data);\r\n");
      out.write("\t\t\t//for(i = 0;i<list.length;i++){\r\n");
      out.write("\t\t\t\t$(\"#infoform\").append('<table style=\" text-align:left;   color: #313131; height:500px;width:500px;font-size:30px \">'\r\n");
      out.write("\t\t\t\t+'<tr ><td><div  style=\" text-align:left; width:150px;  color: #313131; font-size:25px;margin:20px;margin-top:30px;\">店铺ID：</div></td>'\r\n");
      out.write("\t\t\t\t+'<td><div id=\"sid\"  style=\" text-align:left;   color: #313131; font-size:25px\">'+list.storeid+'</div></td></tr>'\r\n");
      out.write("\t\t\t\t+'<tr ><td><div style=\" text-align:left;    color: #313131; font-size:25px;margin:20px;margin-top:30px;;\">店铺名字：</div></td>'\r\n");
      out.write("\t\t\t\t+'<td><div   style=\" text-align:left;   color: #313131; font-size:25px\">'+list.storename+'</div></td></tr>'\r\n");
      out.write("\t\t\t\t+'<tr ><td><div style=\" text-align:left;   color: #313131; font-size:25px;margin:20px;margin-top:30px;\">配送金额：</div></td>'\r\n");
      out.write("\t\t\t\t+'<td><div  style=\" text-align:left;   color: #313131; font-size:25px\">￥'+ list.sendingfee+'元</div></td>'\r\n");
      out.write("\t\t\t\t+'<tr ><td><div style=\" text-align:left;   color: #313131; font-size:25px;margin:20px;margin-top:30px;\">起送金额：</div></td>'\r\n");
      out.write("\t\t\t\t+'<td><div  style=\" text-align:left;   color: #313131; font-size:25px\">￥'+ list.deliverytime+'元</div></td>'\r\n");
      out.write("\t\t\t\t+'<tr ><td><div style=\" text-align:left;   color: #313131; font-size:25px;margin:20px;margin-top:30px;\">配送时间：</div></td>'\r\n");
      out.write("\t\t\t\t+'<td><div  style=\" text-align:left;   color: #313131; font-size:25px\">￥'+ list.deliverycost+'元</div></td>'\r\n");
      out.write("\t\t\t\t+'<td><div style=\"color: #313131; font-size:25px\"></div></td></tr><tr ><td><div style=\" text-align:left;   color: #313131; font-size:25px;margin:20px;margin-top:30px;;\">'\r\n");
      out.write("\t\t\t\t+'店铺logo图片：</div></td><td><div  style=\" text-align:left;   color: #313131; font-size:25px\"><img src=\"/OrderTakeOutFood'+list.storePicture+'\"></div></td></tr>'\r\n");
      out.write("\t\t\t\t+'<tr ><td><div style=\" text-align:left;   color: #313131; font-size:25px;margin:20px;margin-top:30px;\">店铺排名：</div></td>'\r\n");
      out.write("\t\t\t\t+'<td><div  style=\" text-align:left;   color: #313131; font-size:25px\">'+list.rank+'</div></td></tr>'\r\n");
      out.write("\t\t\t\t+'<tr ><td><div style=\" text-align:left;   color: #313131; font-size:25px;margin:20px;margin-top:30px;\">店铺地址：</div></td>'\r\n");
      out.write("\t\t\t\t+'<td><div  style=\" text-align:left;   color: #313131; font-size:25px\">'+list.storeaddr+'</div></td></tr>'\r\n");
      out.write("\t\t\t\t+'<tr ><td><div style=\" text-align:left;   color: #313131; font-size:25px;margin:20px;margin-top:30px;\">店铺号码：</div></td>'\r\n");
      out.write("\t\t\t\t+'<td><div  style=\" text-align:left;   color: #313131; font-size:25px\">'+list.storetel+'</div></td></tr>'\r\n");
      out.write("\t\t\t\t+'<tr ><td><div style=\" text-align:left;   color: #313131; font-size:25px;margin:20px;margin-top:30px;\">是否营业：</div></td>'\r\n");
      out.write("\t\t\t\t+'<td><div  style=\" text-align:left;   color: #313131; font-size:25px\">'+list.storeStatus+'</div></td></tr>'\r\n");
      out.write("\t\t\t\t+'<tr><td colspan=\"2\" style=\"height:100px;margin :20px;float:right\"><a class=\"am-btn am-btn-danger\" href = \"javascript:void(0)\" onclick = \"alert();document.getElementById(\\'light\\').style.display=\\'block\\';document.getElementById(\\'fade\\').style.display=\\'block\\'\"  style=\" font-size:25px; \" >修改</a></td></tr></table>');\r\n");
      out.write("\t\t\t//}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\t//修改\r\n");
      out.write("\tfunction alert(){\r\n");
      out.write("\t$(\"#alertsure\").click(function(){\r\n");
      out.write("\t //$(\"#alertform\").html(id2);\r\n");
      out.write(" \t$.ajax({\r\n");
      out.write("       type: \"POST\",\r\n");
      out.write("       url: \"/OrderTakeOutFood/StoreModifyInfoServlet\",\r\n");
      out.write("       data: $(\"#alertform\").serialize(),\r\n");
      out.write("       async: false,\r\n");
      out.write("\t   datatype:\"json\",\r\n");
      out.write("\t   success:function(data)\r\n");
      out.write("\t   {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t   console.log(data.message);\r\n");
      out.write("\t\t   alert(data.message);\r\n");
      out.write("\t\t  // location.reload();\r\n");
      out.write("\t   }\r\n");
      out.write(" \t\r\n");
      out.write("    }).responseText;\r\n");
      out.write("    \r\n");
      out.write("\treturn false;\r\n");
      out.write(" });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t //判断浏览器是否支持FileReader接口\r\n");
      out.write("    if (typeof FileReader == 'undefined') {\r\n");
      out.write("        document.getElementById(\"xmTanDiv\").InnerHTML = \"<h1>当前浏览器不支持FileReader接口</h1>\";\r\n");
      out.write("        //使选择控件不可操作\r\n");
      out.write("        document.getElementById(\"xdaTanFileImg\").setAttribute(\"disabled\", \"disabled\");\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    //选择图片，马上预览\r\n");
      out.write("    function xmTanUploadImg(obj) {\r\n");
      out.write("        var file = obj.files[0];\r\n");
      out.write("        \r\n");
      out.write("        console.log(obj);console.log(file);\r\n");
      out.write("        console.log(\"file.size = \" + file.size);  //file.size 单位为byte\r\n");
      out.write("\r\n");
      out.write("        var reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("        //读取文件过程方法\r\n");
      out.write("        reader.onloadstart = function (e) {\r\n");
      out.write("            console.log(\"开始读取....\");\r\n");
      out.write("        }\r\n");
      out.write("        reader.onprogress = function (e) {\r\n");
      out.write("            console.log(\"正在读取中....\");\r\n");
      out.write("        }\r\n");
      out.write("        reader.onabort = function (e) {\r\n");
      out.write("            console.log(\"中断读取....\");\r\n");
      out.write("        }\r\n");
      out.write("        reader.onerror = function (e) {\r\n");
      out.write("            console.log(\"读取异常....\");\r\n");
      out.write("        }\r\n");
      out.write("        reader.onload = function (e) {\r\n");
      out.write("            console.log(\"成功读取....\");\r\n");
      out.write("\r\n");
      out.write("            var img = document.getElementById(\"xmTanImg\");\r\n");
      out.write("            img.src = e.target.result;\r\n");
      out.write("            //或者 img.src = this.result;  //e.target == this\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        reader.readAsDataURL(file)\r\n");
      out.write("    }\r\n");
      out.write("    function out(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"/OrderTakeOutFood/CustomerLoginOutServlet\",\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t        async: false,\r\n");
      out.write("\t\t\tdatatype:'json',\r\n");
      out.write("\t\t\tsuccess:function(res){\r\n");
      out.write("\t\t\t\t\talert(res.message);\r\n");
      out.write("\t\t\t\t\twindow.location.href='dp_login.jsp';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("    function DisplayStorername(){\r\n");
      out.write("    \tif(sessionStorage.getItem('store'))\r\n");
      out.write("    \t{\r\n");
      out.write("    \tvar storename = sessionStorage.getItem('store');\r\n");
      out.write("    \t$(\"#storename\").html(storename+\"用户，你好 \");\r\n");
      out.write("    \t}\r\n");
      out.write("    };    \r\n");
      out.write("</script>\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
