/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2018-06-24 16:02:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dp_005forder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<link href=\"css/amazeui.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link href=\"css/admin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<link href=\"css/demo.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<link href=\"css/hmstyle.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t\t<link href=\"css/skin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/amazeui.min.js\"></script>\r\n");
      out.write("<title>店铺订单管理中心</title>\r\n");
      out.write("<style> \r\n");
      out.write("        .black_overlay{ \r\n");
      out.write("            display: none; \r\n");
      out.write("            position: absolute; \r\n");
      out.write("            top: 0%; \r\n");
      out.write("            left: 0%; \r\n");
      out.write("            width: 100%; \r\n");
      out.write("            height: 100%; \r\n");
      out.write("            background-color: black; \r\n");
      out.write("            z-index:1001; \r\n");
      out.write("            -moz-opacity: 0.8; \r\n");
      out.write("            opacity:.80; \r\n");
      out.write("            filter: alpha(opacity=88); \r\n");
      out.write("        } \r\n");
      out.write("        .white_content { \r\n");
      out.write("            display: none; \r\n");
      out.write("            position: absolute; \r\n");
      out.write("            top: 25%; \r\n");
      out.write("            left: 25%; \r\n");
      out.write("            width: 55%; \r\n");
      out.write("            height: auto; \r\n");
      out.write("            padding: 20px; \r\n");
      out.write("            border: 10px solid orange; \r\n");
      out.write("            background-color: white; \r\n");
      out.write("            z-index:1002; \r\n");
      out.write("            overflow: auto; \r\n");
      out.write("        } \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:#F8F8F8;min-width:1500px;\">\r\n");
      out.write("\t\t<!--顶部导航条1 -->\r\n");
      out.write("\t\t<div name=\"导航1\" style=\"width:auto;margin: 0 auto;background-color: #333;margin-top: 0px;margin-right: auto;margin-bottom: 0px;margin-left: auto;height: 32px;line-height: 32px;min-width:1500px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-l\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage\" style=\"color:#ddd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-logo\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t欢迎使用网上订餐网站！\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-r\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage login\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd login\" ><a id=\"storename\" target=\"_top\" style=\"color:#ddd\"></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage login\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd login\" ><a   target=\"_top\" style=\"color:#ddd\" onclick=\"out()\">退出登陆 </a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t<!-- 弹出框1-弹出订单内容 -->\r\n");
      out.write("       \t<div id=\"light\" class=\"white_content\" >\r\n");
      out.write("       \t\t\t \t<a style=\"width:100%;font-size:25px;text-align:right;float:right; margin :5px;color:#ebebeb\" href=\"javascript:void(0)\" onclick=\"document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none';location.reload();\">关闭</a>\r\n");
      out.write("       \t\t\t \t<div id=\"ordercontent\">\r\n");
      out.write("       \t\t\t \t</div>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div id=\"fade\" class=\"black_overlay\"></div>\r\n");
      out.write("\t\t<!--顶部导航条2-->\r\n");
      out.write("\t\t<div name=\"导航2\" style=\"height:130px;width:auto;background:white\">\r\n");
      out.write("\t\t\t\t\t<!-- icon -->\r\n");
      out.write("\t\t\t\t\t<div style=\"margin:0px 0px 0px 0px;;vertical-align:middle; height:100px;width:300px;float:left\">\r\n");
      out.write("\t\t\t\t\t\t<div  style=\"height:80px;width:180px;float:left \">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"image/logo.JPG\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div   style=\"font-size:25px;margin-top:50px;font-weight:600;height:80px;vertical-align:middle; width:100px; float:left \">\r\n");
      out.write("\t\t\t\t\t\t\t 网上订餐\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 导航条2.1 -->\r\n");
      out.write("\t\t\t\t\t<div style=\"text-align:center; margin-left:auto; margin-right:auto; margin-top:5px;text-align:center;vertical-align:middle; height:100px;width:740px\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\" #\" style=\" margin:40px;font-size:60px;font-weight:600 ;vertical-align:middle\">店铺管理界面</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"clear \"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<!-- 店铺订单具体内容 -->\r\n");
      out.write("\t\t<div style=\" width:1200px;margin-bottom:20px;  height:1200px;   color: #444444; margin-top: 20px;margin-right: auto;margin-bottom: 0px;margin-left: auto\">\r\n");
      out.write("\t\t\t<!-- 左边导航框 -->\r\n");
      out.write("\t\t<div style=\"background-color:white; float:left;width:300px;height:1000px\">\r\n");
      out.write("\t\t\t\t<!-- 订单管理 -->\r\n");
      out.write("\t\t\t\t<div class=\"dd\" style=\"margin-top:50px;font-size:30px;height:80px; \">\r\n");
      out.write("\t\t\t\t\t<a href=\"dp_food.jsp\" style=\" margin-top:20px;font-size:25px;\">商品管理</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t<div class=\"zh\" style=\"background-color:#ebebeb;margin-top:20px;font-size:30px;height:80px;border-bottom: 2px solid #F03726; \">\r\n");
      out.write("\t\t\t\t\t<a href=\"\"  style=\"font-weight:600;color: #E4393C; margin-top:20px;font-size:25px;\">订单管理</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"zh\" style=\" margin-top:20px;height:80px\">\r\n");
      out.write("\t\t\t\t\t<a href=\"dp_my.jsp\"  style=\" margin-top:20px;font-size:25px;\">店铺信息管理</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<!--  内容框 -->\r\n");
      out.write("\t\t<div style=\"margin-left:10px;background-color:white; float:left;width:880px;height:1000px\">\r\n");
      out.write("\t\t\t\t<div class=\"introduce\">\r\n");
      out.write("\t\t\t\t\t<div class=\"introduceMain\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"am-tabs\" data-am-tabs>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 页内菜单栏 -->\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"am-avg-sm-4 am-tabs-nav am-nav am-nav-tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"am-active\" style=\"height:auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"index-needs-dt-txt\" style=\"font-size:25px\">未接受订单</span></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:auto;width:25%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"index-needs-dt-txt\" style=\"font-size:25px\">已接收订单</span></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"index-needs-dt-txt\" style=\"font-size:25px\">已完成订单</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:auto;width:25%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"index-needs-dt-txt\" style=\"font-size:25px\">搜索订单</span></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"am-tabs-bd\">\r\n");
      out.write("\t\t\t\t\t\t\t<!--未接受订单 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"am-tab-panel am-fade am-in am-active\" >\r\n");
      out.write("\t\t\t\t\t\t\t \t<div id=\"orderl\" style=\"width:auto;height:auto ; \">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form id=\"not_accept\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"orderstatus\"  name=\"orderstatus\" type=\"hidden\" value=0>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 未接受订单信息 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 已接收订单 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"am-tab-panel am-fade\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 已接收订单信息 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"orderl2\" style=\"width:auto;height:auto ; \">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form id=\"already_accept\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"orderstatus\"  name=\"orderstatus\" type=\"hidden\" value=1>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!--  已完成订单 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"am-tab-panel am-fade\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 已完成订单信息 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"orderl3\" style=\"width:auto;height:auto ; \">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form id=\"finish\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"orderstatus\"  name=\"orderstatus\" type=\"hidden\" value=2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--  搜索订单 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"am-tab-panel am-fade\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 搜索框-->\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"   width: 90%;height: 40px; border: 1px solid #e5e5e5;margin-left:50px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"searchInput\" style=\"  font-size:20px;  float: left;display:inline;width:80%;height: 38px; ;font-size: 14px;color: #535353;border: none;background: none;margin-left:5px \" name=\"index_none_header_sysc\" type=\"text\" placeholder=\"搜索商家，美食\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"ai-topsearch\" class=\"submit am-btn\" style=\"height:38px;width:100px;display:inline \" value=\"搜索\" index=\"1\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 查询内容 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div  style=\"border: 1px dashed #e5e5e5;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\t \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 脚注 -->\r\n");
      out.write("\t\t<div class=\"footer \" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-hd \" >\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \"> </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"home.jsp\">商城首页</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">支付宝</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">物流</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-bd \" >\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">关于我们</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">合作伙伴</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">联系我们</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">网站地图</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t\r\n");
      out.write("\tDisplayStorername();\r\n");
      out.write("\t//时间戳转换\r\n");
      out.write("\tfunction timestampToTime(timestamp) {\r\n");
      out.write("\t   \t var date = new Date(timestamp);//时间戳为10位需*1000，时间戳为13位的话不需乘1000\r\n");
      out.write("\t  \t  Y = date.getFullYear() + '-';\r\n");
      out.write("\t  \t  M = (date.getMonth()+1 < 10 ? '0'+(date.getMonth()+1) : date.getMonth()+1) + '-';\r\n");
      out.write("\t  \t  D = date.getDate() + ' ';\r\n");
      out.write("\t  \t  h = date.getHours() + ':';\r\n");
      out.write("\t  \t  m = date.getMinutes() + ':';\r\n");
      out.write("\t  \t  s = date.getSeconds();\r\n");
      out.write("\t  \t  return Y+M+D+h+m+s;\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t//订单状态转义\r\n");
      out.write("\t\t\tfunction DisplayOrderStatus(status){\r\n");
      out.write("\t\t\tif(status == 1)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\treturn \"已接单\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if(status == 0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\treturn \"未接单\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\telse if(status == 2)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\treturn \"已完成\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\telse if(status ==3)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\treturn \"异常\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\t\r\n");
      out.write("\t\t//店铺展示未接受订单\t\r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t\t\turl:\"/OrderTakeOutFood/StoreDisplayOrderServlet\",\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t        data: $(\"#not_accept\").serialize(),\r\n");
      out.write("\t        async: false,\r\n");
      out.write("\t\t\tdatatype:'json',\r\n");
      out.write("\t\t\tsuccess:function(res){\r\n");
      out.write("\t\t\t\tvar list = res.data.orderList;\r\n");
      out.write("\t\t\t\tconsole.log(res.data);\r\n");
      out.write("\t\t\t\tfor(var i = 0;i<list.length;i++){\r\n");
      out.write("\t\t\t\t\t$(\"#orderl\").append('<div style=\"padding:10px;margin:20px;width:350px;float:left;vertical-align:middle;height:auto;float:left;border: 1px dashed #e5e5e5;\">'\r\n");
      out.write("\t\t\t\t\t\t+'<div id =\\'ordernumber\\'' + i + ' style=\"text-align:left;  font-size:20px;margin-top:10px \">订单编号:'+list[i].ordernumber+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">订餐人姓名：'+list[i].personalName+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">订单人电话：'+list[i].usertel+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">配送时间：'+list[i].deliverytime+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">订单金额：'+list[i].sumprice+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">日期：'+timestampToTime(list[i].orderTime.time)+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"font-size:20px;   font-family:黑体 ;margin-top:10px\">订餐内容：<a class=\"am-btn am-btn-danger\" href=\"javascript:void(0)\" onclick=\"order(this);document.getElementById(\\'light\\').style.display=\\'block\\';document.getElementById(\\'fade\\').style.display=\\'block\\'\" style=\"font-size:15px;font-weight: bold;  font-family:黑体\"> 查看</a>'\r\n");
      out.write("\t\t\t\t\t\t+'<div name=\"num\" style=\"display:none\" >'+list[i].ordernumber+'</div></div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"font-size:20px;   font-family:黑体 ;margin-top:10px\">状态：\t'+DisplayOrderStatus(list[i].orderStatus)+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"font-size:20px;   font-family:黑体 ;margin-top:10px\">订单操作：<a id = \"acceptorder'+ i +'\" class=\"am-btn am-btn-danger\"  style=\"font-size:15px;font-weight: bold;  font-family:黑体\"> 接受订单</a></div>')\r\n");
      out.write("\t\t\t\t//console.log(list[i]);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t   \t\t$(\"#acceptorder\"+i).bind(\"click\",{ordernumber:list[i].ordernumber},Acceptorder)\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t   });\r\n");
      out.write("\t\t\r\n");
      out.write("\t   //接受订单\r\n");
      out.write("\t   function Acceptorder(event){\r\n");
      out.write("\t\t   var order = {\r\n");
      out.write("\t\t\t\t   ordernumber:event.data.ordernumber,\r\n");
      out.write("\t\t            orderstatus:\"1\"\t\t            \r\n");
      out.write("\t\t        };\r\n");
      out.write("\t\t  // console.log(ordernumber[i-1])\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\turl:\"/OrderTakeOutFood/OrderAcceptServlet\",\r\n");
      out.write("\t\t\t\tdata:order,\r\n");
      out.write("\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\tdatatype:'json',\r\n");
      out.write("\t\t\t\tsuccess:function(res){\r\n");
      out.write("\t\t\t\t\tif(res.code == 200)\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\talert('接受订单成功')\r\n");
      out.write("\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\talert('接受订单失败')\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t   //店铺展示已接收订单\r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t\t\turl:\"/OrderTakeOutFood/StoreDisplayOrderServlet\",\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t        data: $(\"#already_accept\").serialize(),\r\n");
      out.write("\t        async: false,\r\n");
      out.write("\t\t\tdatatype:'json',\r\n");
      out.write("\t\t\tsuccess:function(res){\r\n");
      out.write("\t\t\t\tvar list = res.data.orderList;\r\n");
      out.write("\t\t\t\tconsole.log(res.data);\r\n");
      out.write("\t\t\t\tfor(var i = 0;i<list.length;i++){\r\n");
      out.write("\t\t\t\t\t$(\"#orderl2\").append('<div style=\"padding:10px;margin:20px;width:350px;float:left;vertical-align:middle;height:auto;float:left;border: 1px dashed #e5e5e5;\">'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">订单编号:'+list[i].ordernumber+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">订餐人姓名：'+list[i].personalName+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">订单人电话：'+list[i].usertel+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">配送时间：'+list[i].deliverytime+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">订单金额：'+list[i].sumprice+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">日期：'+timestampToTime(list[i].orderTime.time)+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"font-size:20px;   font-family:黑体 ;margin-top:10px\">订餐内容：<a class=\"am-btn am-btn-danger\" href=\"javascript:void(0)\" onclick=\"order(this);document.getElementById(\\'light\\').style.display=\\'block\\';document.getElementById(\\'fade\\').style.display=\\'block\\'\" style=\"font-size:15px;font-weight: bold;  font-family:黑体\"> 查看</a>'\r\n");
      out.write("\t\t\t\t\t\t+'<div name=\"num\" style=\"display:none\" >'+list[i].ordernumber+'</div></div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"font-size:20px;   font-family:黑体 ;margin-top:10px\">状态：\t'+DisplayOrderStatus(list[i].orderStatus)+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"font-size:20px;   font-family:黑体 ;margin-top:10px\">订单操作：<a id = \"finishorder'+i+'\" class=\"am-btn am-btn-danger\"  style=\"font-size:15px;font-weight: bold;  font-family:黑体\"> 完成订单</a></div>')\r\n");
      out.write("\t\t\t\t//console.log(list[i]);\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#finishorder\"+i).bind(\"click\",{ordernumber:list[i].ordernumber},Finishorder)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t   })\r\n");
      out.write("\t   \r\n");
      out.write("\t //完成订单\r\n");
      out.write("\t   function Finishorder(event){\r\n");
      out.write("\t\t   \r\n");
      out.write("\t   \t   var order = {\r\n");
      out.write("\t   \t\t\t   ordernumber:event.data.ordernumber,\r\n");
      out.write("\t   \t            orderstatus:\"2\"\r\n");
      out.write("\t   \t            \r\n");
      out.write("\t   \t        };\r\n");
      out.write("\t   \t  // console.log(ordernumber[i-1])\r\n");
      out.write("\t   \t\t$.ajax({\r\n");
      out.write("\t   \t\t\ttype:\"POST\",\r\n");
      out.write("\t   \t\t\turl:\"/OrderTakeOutFood/OrderAcceptServlet\",\r\n");
      out.write("\t   \t\t\tdata:order,\r\n");
      out.write("\t   \t\t\tasync:false,\r\n");
      out.write("\t   \t\t\tdatatype:'json',\r\n");
      out.write("\t   \t\t\tsuccess:function(res){\r\n");
      out.write("\t   \t\t\t\tif(res.code == 200)\r\n");
      out.write("\t   \t\t\t\t\t{\r\n");
      out.write("\t   \t\t\t\t\talert('完成订单成功')\r\n");
      out.write("\t   \t\t\t\t\tlocation.reload();\r\n");
      out.write("\t   \t\t\t\t\t}\r\n");
      out.write("\t   \t\t\t\telse\r\n");
      out.write("\t   \t\t\t\t\t{\r\n");
      out.write("\t   \t\t\t\t\talert('完成订单失败')\r\n");
      out.write("\t   \t\t\t\t\t}\r\n");
      out.write("\t   \t\t\t}\r\n");
      out.write("\t   \t\t\t})\r\n");
      out.write("\t   \t\t};\r\n");
      out.write("\t   //店铺展示已完成订单\r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t\t\turl:\"/OrderTakeOutFood/StoreDisplayOrderServlet\",\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t        data: $(\"#finish\").serialize(),\r\n");
      out.write("\t        async: false,\r\n");
      out.write("\t\t\tdatatype:'json',\r\n");
      out.write("\t\t\tsuccess:function(res){\r\n");
      out.write("\t\t\t\tvar list = res.data.orderList;\r\n");
      out.write("\t\t\t\tconsole.log(res.data);\r\n");
      out.write("\t\t\t\tfor(var i = 0;i<list.length;i++){\r\n");
      out.write("\t\t\t\t\t$(\"#orderl3\").append('<div style=\"padding:10px;margin:20px;width:350px;float:left;vertical-align:middle;height:auto;float:left;border: 1px dashed #e5e5e5;\">'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">订单编号:'+list[i].ordernumber+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">订餐人姓名：'+list[i].personalName+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">订单人电话：'+list[i].usertel+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">配送时间：'+list[i].deliverytime+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">订单金额：'+list[i].sumprice+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"text-align:left;  font-size:20px;margin-top:10px \">日期：'+timestampToTime(list[i].orderTime.time)+'</div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"font-size:20px;   font-family:黑体 ;margin-top:10px\">订餐内容：<a class=\"am-btn am-btn-danger\" href=\"javascript:void(0)\" onclick=\"order(this);document.getElementById(\\'light\\').style.display=\\'block\\';document.getElementById(\\'fade\\').style.display=\\'block\\'\" style=\"font-size:15px;font-weight: bold;  font-family:黑体\"> 查看</a>'\r\n");
      out.write("\t\t\t\t\t\t+'<div name=\"num\" style=\"display:none\" >'+list[i].ordernumber+'</div></div>'\r\n");
      out.write("\t\t\t\t\t\t+'<div style=\"font-size:20px;   font-family:黑体 ;margin-top:10px\">状态：\t'+DisplayOrderStatus(list[i].orderStatus)+'</div></div>')\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t   })\r\n");
      out.write("\t   });\r\n");
      out.write("//点击查看未接受的订餐内容\r\n");
      out.write("var order=function (obj){\r\n");
      out.write("\t\tvar num = $(obj).next().html();\r\n");
      out.write("\t\tconsole.log(num)\r\n");
      out.write("\t\t//alert(num)\r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t\t\turl:\"/OrderTakeOutFood/DisplayOrderContentServlet\",\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t        data: {ordernumber:num},\r\n");
      out.write("\t        async: false,\r\n");
      out.write("\t\t\tdatatype:'json',\r\n");
      out.write("\t\t\tsuccess:function(res){\r\n");
      out.write("\t\t\t\tvar list = res.data.ordercontentlist;\r\n");
      out.write("\t\t\t\tconsole.log(res.data);\r\n");
      out.write("\t\t\t\tvar t = 0;\r\n");
      out.write("\t\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\t\tstr +='<div style=\"height:auto;  width:auto;font-size:30px;text-align:center; margin :10px;font-weight:600\">订单内容</div>'\r\n");
      out.write("\t\t\t\t \t+'<div  style=\" text-align:center; margin :10px\"><table style=\"margin-left:auto;margin-right:auto;   \">';\r\n");
      out.write("\t\t\t\tfor(var i = 0;i<list.length;i++){\r\n");
      out.write("\t\t\t\t\tstr +='<tbody><tr><td style=\" font-size:25px; margin :10px\">商品名字：'+list[i].foodname+'</td></tr>'\r\n");
      out.write("\t\t\t\t\tt = i;\r\n");
      out.write("\t\t\t\t}  \r\n");
      out.write("\t\t\t\t\t \tstr +='</table></div>'\r\n");
      out.write("\t\t\t\t\t \t+'<div style=\"height:auto;  width:100%;font-size:30px;text-align:center;font-weight:600\">配送信息</div>'\r\n");
      out.write("\t\t\t\t\t \t+'<div  style=\" text-align:center; margin :10px\"><table style=\"margin-left:auto;margin-right:auto;   \"><tbody>'\r\n");
      out.write("\t\t\t\t\t \t+'<tr><td style=\" font-size:25px; margin :10px\">收获地址：'+ list[t].useraddr +'</td></tr>'\r\n");
      out.write("\t\t\t\t\t \t+'<tr><td style=\" font-size:25px; margin :10px\">订单号：'+list[t].orderNumber+'</td></tr></table>';\t\r\n");
      out.write("\t\t\t\t\t $(\"#ordercontent\").append(str);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction dpbtn(obj){\r\n");
      out.write("\t\t//alert($(obj).text());\r\n");
      out.write("\t\tif($(obj).text()==\"营业\"){\r\n");
      out.write("\t\t\t$(obj).html(\"打烊\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(obj).html(\"营业\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction out(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"/OrderTakeOutFood/CustomerLoginOutServlet\",\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t        async: false,\r\n");
      out.write("\t\t\tdatatype:'json',\r\n");
      out.write("\t\t\tsuccess:function(res){\r\n");
      out.write("\t\t\t\t\talert(res.message);\r\n");
      out.write("\t\t\t\t\twindow.location.href='dp_login.jsp';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction DisplayStorername(){\r\n");
      out.write("    \tif(sessionStorage.getItem('store'))\r\n");
      out.write("    \t{\r\n");
      out.write("    \tvar storename = sessionStorage.getItem('store');\r\n");
      out.write("    \t$(\"#storename\").html(storename+\"用户，你好 \");\r\n");
      out.write("    \t}\r\n");
      out.write("    };      \r\n");
      out.write("</script>\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
