/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2018-06-21 19:43:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<link href=\"css/amazeui.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link href=\"css/admin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<link href=\"css/demo.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link href=\"css/hmstyle.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t\t<link href=\"css/skin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/amazeui.min.js\"></script>\r\n");
      out.write("<title>全部商铺列表</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:#F8F8F8;min-width:1500px;\">\r\n");
      out.write("\t\t\t\t<!--顶部导航条1 -->\r\n");
      out.write("\t\t\t\t<div name=\"导航1\" style=\"width:auto;margin: 0 auto;background-color: #333;margin-top: 0px;margin-right: auto;margin-bottom: 0px;margin-left: auto;height: 32px;line-height: 32px;min-width:1500px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-l\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage\" style=\"color:#ddd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-logo\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t欢迎使用网上订餐网站！\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-r\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage login\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd login\" ><span target=\"_top\" id=\"username\" style=\"color:#ddd\"></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t|\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage register\" style=\"color:#ddd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd register\"><a  target=\"_top\" style=\"color:#ddd\" onclick = \"loginout()\">注销</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage home\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd\"><a href=\"dp_register.jsp\" target=\"_top\" style=\"color:#ddd\">开店申请</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage my-shangcheng\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd MyShangcheng\"><a href=\"my.jsp\" target=\"_top\" style=\"color:#ddd\"><i class=\"am-icon-user am-icon-fw\"></i>个人中心</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage mini-cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd\"><a id=\"mc-menu-hd\" href=\"#\" target=\"_top\" style=\"color:#ddd\"><i class=\"am-icon-shopping-cart  am-icon-fw\"></i><span>购物车</span><strong id=\"J_MiniCartNum\" class=\"h\">0</strong></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage favorite\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd\"><a href=\"#\" target=\"_top\" style=\"color:#ddd\"><i class=\"am-icon-heart am-icon-fw\"></i><span>收藏夹</span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--顶部导航条2-->\r\n");
      out.write("\t\t<div name=\"导航2\" style=\"height:130px;width:auto;background:white\">\r\n");
      out.write("\t\t\t\t\t<!-- icon -->\r\n");
      out.write("\t\t\t\t\t<div style=\"margin:0px 0px 0px 0px;;vertical-align:middle; height:100px;width:300px;float:left\">\r\n");
      out.write("\t\t\t\t\t\t<div  style=\"height:80px;width:180px;float:left \">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"image/logo.JPG\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div   style=\"font-size:25px;margin-top:50px;font-weight:600;height:80px;vertical-align:middle; width:100px; float:left \">\r\n");
      out.write("\t\t\t\t\t\t\t 网上订餐\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--悬浮搜索框-->\r\n");
      out.write("\t\t\t\t\t<div style=\"float: right;  margin-top:40px;width: 290px;height: 38px; border: 1px solid #e5e5e5;\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"searchInput\" style=\"    float: left;display: block;width: 225px;height: 38px; ;font-size: 14px;color: #535353;border: none;background: none;margin-left:5px \" name=\"index_none_header_sysc\" type=\"text\" placeholder=\"搜索商家，美食\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"ai-topsearch\" class=\"submit am-btn\" style=\"height:38px;width:100px float: left \" value=\"搜索\" index=\"1\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 导航条2.1 -->\r\n");
      out.write("\t\t\t\t\t<div style=\"text-align:center; margin-left:auto; margin-right:auto; margin-top:5px;text-align:center;vertical-align:middle; height:100px;width:740px\">\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\"float:left;margin:40px;font-size:30px\">首页</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ddetail.jsp\" style=\"float:left;margin:40px;font-size:30px\">我的订单</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"dp_register.jsp\" style=\"float:left;margin:40px;font-size:30px\">入驻加盟</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\"float:left;margin:40px;font-size:30px\">社会责任</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"clear \"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!--商品列表 -->\r\n");
      out.write("\t\t\t\t<div class=\"am-container shoplist \" style=\"margin-top:9px\">\r\n");
      out.write("\t\t\t\t\t\t<!--商品列表（标题行）-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"shopTitle \"  >\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"padding: 18px 0 18px 0;margin: 0 10px;position: relative;overflow: hidden;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:50px;height:50px;display: inline-block;float:left\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"image/icon.JPG\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"vertical-align:middle; margin:10px;display: inline-block;float:left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>商家分类</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display: inline-block;color:#898989;vertical-align:middle; margin:10px;display: inline-block;float:left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t <h4 >全部</h4>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display: inline-block;color:#898989;vertical-align:middle; margin:10px;display: inline-block;float:left\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t <h4 style=\"display: inline-block\">美食   </h4>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display: inline-block;color:#898989;vertical-align:middle; margin:10px;display: inline-block;float:left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t <h4 style=\"display: inline-block\"> 正餐优选   </h4>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display: inline-block;color:#898989;vertical-align:middle; margin:10px;display: inline-block;float:left\">\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t  <h4 style=\"display: inline-block\">超市    </h4>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display: inline-block;color:#898989;vertical-align:middle; margin:10px;display: inline-block;float:left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <h4 style=\"display: inline-block\">精选小吃    </h4>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display: inline-block;color:#898989;vertical-align:middle; margin:10px;display: inline-block;float:left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <h4 style=\"display: inline-block\"> 鲜果购    </h4>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display: inline-block;color:#898989;vertical-align:middle; margin:10px;display: inline-block;float:left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <h4 style=\"display: inline-block\">下午茶 </h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!--商品列表（第一行）-->\r\n");
      out.write("\t\t\t\t\t    <div class=\"am-g am-g-fixed \" id = \"storelist\" style=\"background:white\">\t\r\n");
      out.write("\t\t\t\t\t  \t</div>\r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t<div class=\"clear \"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t<!-- 添加分页 (需要添加变量以及修改页面控制层) -->\r\n");
      out.write("\t\t\t\t<div class=\"am-container \">\r\n");
      out.write("\t\t\t\t<form name=\"f1\" method=\"POST\"\">\r\n");
      out.write("           \t\t<div class=\"footer-hd \" align=\"center\"> \t\r\n");
      out.write("                    \t第？页\r\n");
      out.write("                    \t<b>|</b>\r\n");
      out.write("                    \t共？页 <\r\n");
      out.write("                    \t<b>|</b>\r\n");
      out.write("                    \t<a href=\"#\">首页</a>\r\n");
      out.write("                    \t<b>|</b>\r\n");
      out.write("                    \t<a href=\"#\"> 上一页</a>\r\n");
      out.write("                    \t<b>|</b>\r\n");
      out.write("                    \t<a href=\"#\"> 下一页</a>\r\n");
      out.write("                    \t<b>|</b>\r\n");
      out.write("                    \t<a href=\"#\">最后一页</a>\r\n");
      out.write("                    \t<b>|</b>\r\n");
      out.write("                    \t转到第:<input type=\"text\" id=\"pagenum\" name=\"page\" size=\"8\">页\r\n");
      out.write("                    \t<input type=\"button\" value=\"GO\" onClick =\"jump()\" >\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\tfunction jump(){\r\n");
      out.write("\t\t\t\t\t  pages = document.getElementById(\"pagenum\").value;\r\n");
      out.write("\t\t\t\t\t  if(pages == \"\")\r\n");
      out.write("\t\t\t\t\t\t  pages=1;\r\n");
      out.write("\t\t\t\t\t  window.location.href = \"PageQueryCtrl?pages=\"+ pages;\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 脚注 -->\r\n");
      out.write("\t\t\t\t<div class=\"footer \" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-hd \" >\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \"> </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"home.jsp\">商城首页</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">支付宝</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">物流</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-bd \" >\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">关于我们</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">合作伙伴</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">联系我们</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">网站地图</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script typr=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("DisplayUsername();\r\n");
      out.write("$.ajax({\r\n");
      out.write("\turl:\"/OrderTakeOutFood/StoreAllDisplayServlet\",\r\n");
      out.write("\ttype:'get',\r\n");
      out.write("\tdatatype:'json',\r\n");
      out.write("\tsuccess:function(res){\r\n");
      out.write("\t\tvar str = \"\";\r\n");
      out.write("\t\tvar list = res.data.storeList;\r\n");
      out.write("\t\tconsole.log(res.data);\r\n");
      out.write("\t\tfor(i = 0;i<list.length;i++){\r\n");
      out.write("\t\t\tstr += \"<div class=\\\"am-u-sm-3 \\\"><div class=\\\"activityMain \\\"style=\\\"margin:5px\\\">\"+\"<a href=\\\"foodlist.jsp?storeid=\" + list[i].storeid +\"\\\">\"+\r\n");
      out.write("\t\t\t\"<img src=\\\"\"+\"/OrderTakeOutFood\"+list[i].storePicture +\"\\\"></img></a></div><div class=\\\"info \\\"><h3>商店名字: \"+\r\n");
      out.write("\t\t\tlist[i].storename+\"<br />评分:\"+list[i].rank+\"<br />配送费:\"+list[i].deliverycost+\r\n");
      out.write("\t\t\t\"</h3></div></div>\";\r\n");
      out.write("\t\t\tconsole.log(str);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#storelist\").append(str);\r\n");
      out.write("\t}\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("function DisplayUsername(){\r\n");
      out.write("\t\tif(sessionStorage.getItem('user'))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\tvar userJsonStr = sessionStorage.getItem('user');\r\n");
      out.write("\t\t\tuserEntity = JSON.parse(userJsonStr);\r\n");
      out.write("\t\t\tvar username = userEntity.username ;\r\n");
      out.write("\t\t\t$(\"#username\").html(username);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("};\r\n");
      out.write("function loginout(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\turl:\"CustomerLoginOutServlet\",\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tdatatype:\"json\",\r\n");
      out.write("\t\tsuccess: function (data)  \r\n");
      out.write("        {  \r\n");
      out.write("      \t\r\n");
      out.write("     \t   if(data.code == 200)\r\n");
      out.write("     \t   {\r\n");
      out.write("     \t\t  sessionStorage.removeItem('user');\r\n");
      out.write("     \t\t$(location).attr('href', '/OrderTakeOutFood/login.jsp');\r\n");
      out.write("     \t   \talert(data.message)\r\n");
      out.write("     \t   \t\t\r\n");
      out.write("     \t   }else{\r\n");
      out.write("     \t\t   alert(data.message);\r\n");
      out.write("     \t   }\t\t   \t            \t\r\n");
      out.write("          },\r\n");
      out.write("        error: function()\r\n");
      out.write("        {\r\n");
      out.write("      \t  console.log(\"提交错误\")\r\n");
      out.write("        }\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
