/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2018-06-20 18:03:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\t<head lang=\"en\">\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>登录</title>\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("\t\t<meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("\t\t<meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("\t\t<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" />\r\n");
      out.write("\t\t<link href=\"css/amazeui.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link href=\"css/admin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<link href=\"css/demo.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<link href=\"css/hmstyle.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t\t<link href=\"css/skin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/amazeui.css\" />\r\n");
      out.write("\t\t<link href=\"css/dlstyle.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("\t\t<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body style=\"background-color:#F8F8F8;min-width:1500px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\t<!--顶部导航条 -->\r\n");
      out.write("\t\t<div name=\"导航1\" style=\"width:auto;margin: 0 auto;background-color: #333;margin-top: 0px;margin-right: auto;margin-bottom: 0px;margin-left: auto;height: 32px;line-height: 32px;min-width:1500px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-l\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage\" style=\"color:#ddd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-logo\"     style=\"font-size: 14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t欢迎使用网上订餐网站！\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-r\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage home\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd\"><a href=\"home.jsp\" target=\"_top\" style=\"font-size: 14px;color:#ddd\">首页</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage home\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd\"><a href=\"dp_register.jsp\" target=\"_top\" style=\"font-size: 14px;color:#ddd\">开店申请</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 中间模块 -->\r\n");
      out.write("\t\t<div style=\"height:500px;width:auto\" >\r\n");
      out.write("\t\t\t<div class=\"login-main\" style=\"background-color:white\">\r\n");
      out.write("\t\t\t\t<div   style=\"width:360px;height:430px;position: absolute;margin-top: 20px;margin-left: 120px;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"image/logo.png\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"login-box\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"title\">登录</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"login-form\">\r\n");
      out.write("\t\t\t\t\t\t  <form id = login_form>\r\n");
      out.write("\t\t\t\t\t\t\t   <div class=\"user-name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <label for=\"user\"><i class=\"am-icon-user\"></i></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"text\" name=\"username\" id=\"username\" placeholder=\"邮箱/手机号\" onchange = \"verify()\">\r\n");
      out.write("                 \t\t\t\t\t\r\n");
      out.write("                 </div>\r\n");
      out.write("                 <div class=\"user-pass\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <label for=\"password\"><i class=\"am-icon-lock\"></i></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"password\" name=\"userpwd\" id=\"userpwd\" placeholder=\"请输入密码\">\r\n");
      out.write("                 </div>\r\n");
      out.write("              </form>\r\n");
      out.write("           </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"login-links\">\r\n");
      out.write("                <label for=\"remember-me\"><input id=\"remember-me\" type=\"checkbox\">记住密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"am-fr\">忘记密码</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"register.jsp\" class=\"zcnext am-fr am-btn-default\">注册</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br />\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"am-cf\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"\" value=\"登 录\" class=\"am-btn am-btn-primary am-btn-sm\" onclick = \"login()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"spinfo\" style = \"color:red\"></span>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"footer \" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-hd \" >\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \"> </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"home.jsp\">首页</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">支付宝</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">物流</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-bd \" >\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">关于我们</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">合作伙伴</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">联系我们</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"# \">网站地图</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t\t\r\n");
      out.write("function login(){\r\n");
      out.write("       //按钮单击时执行\r\n");
      out.write("        $.ajax({\r\n");
      out.write("              type: \"POST\",\r\n");
      out.write("              url: \"/OrderTakeOutFood/CustromerLoginServlet\",\r\n");
      out.write("              data: $(\"#login_form\").serialize(),\r\n");
      out.write("              async: false,\r\n");
      out.write("              datatype:\"json\",\r\n");
      out.write("              \r\n");
      out.write("              success: function (data)  \r\n");
      out.write("              {  \r\n");
      out.write("            \t\r\n");
      out.write("           \t   if(data.code == 200)\r\n");
      out.write("           \t   {\r\n");
      out.write("           \t\tvar user = data.data.user;\r\n");
      out.write("         \t\tsessionStorage.setItem(\"user\", JSON.stringify(user));\r\n");
      out.write("           \t   $(location).attr('href', '/OrderTakeOutFood/home.jsp');\r\n");
      out.write("           \t   }else{\r\n");
      out.write("           \t\t   alert(data.message);\r\n");
      out.write("           \t   }\t\t   \t            \t\r\n");
      out.write("  \t          },\r\n");
      out.write("              error: function()\r\n");
      out.write("              {\r\n");
      out.write("            \t  console.log(dasdas)\r\n");
      out.write("              }\r\n");
      out.write("           \t})\r\n");
      out.write("           \r\n");
      out.write("\t\treturn false;\r\n");
      out.write("        };\r\n");
      out.write("function verify() {\r\n");
      out.write("           var state = false;\r\n");
      out.write("           $(\"#username\").focus(function () {\r\n");
      out.write("               if (state == false) {\r\n");
      out.write("                   $(this).val('');\r\n");
      out.write("               }\r\n");
      out.write("           })\r\n");
      out.write("           $(\"#username\").blur(function () {\r\n");
      out.write("               if ($(this).val() == '') {\r\n");
      out.write("                   $(\"#spinfo\").text(\"邮箱不能为空\");\r\n");
      out.write("                   $(this).focus();\r\n");
      out.write("               }\r\n");
      out.write("               else {\r\n");
      out.write("                   if (/^\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*$/.test($(this).val()) == false) {\r\n");
      out.write("                       $(\"#spinfo\").text(\"邮箱格式不正确，请重新填写\");\r\n");
      out.write("                       $(this).focus();\r\n");
      out.write("                   }\r\n");
      out.write("                   else {\r\n");
      out.write("                       $(\"#spinfo\").text('');\r\n");
      out.write("                       state=true;\r\n");
      out.write("                   }\r\n");
      out.write("               }\r\n");
      out.write("           })\r\n");
      out.write("       };\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
