/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2018-06-24 09:43:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sumlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>结算页面</title>\r\n");
      out.write("\t\t<link href=\"css/amazeui.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link href=\"css/admin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link type=\"text/css\" href=\"css/optstyle.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link type=\"text/css\" href=\"css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/jquery-1.7.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/quick_links.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/amazeui.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/jquery.imagezoom.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/jquery.flexslider.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/list.js\"></script>\r\n");
      out.write("\t\t<script src =\"js/verify.js\"></script>\r\n");
      out.write("\t\t<link href=\"css/personal.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<link href=\"css/addstyle.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<script src=\"js/jquery.min1.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<link href=\"css/demo.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link href=\"css/hmstyle.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t\t<link href=\"css/skin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link href=\"css/admin.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style> \r\n");
      out.write("        .black_overlay{ \r\n");
      out.write("            display: none; \r\n");
      out.write("            position: absolute; \r\n");
      out.write("            top: 0%; \r\n");
      out.write("            left: 0%; \r\n");
      out.write("            width: 100%; \r\n");
      out.write("            height: 100%; \r\n");
      out.write("            background-color: black; \r\n");
      out.write("            z-index:1001; \r\n");
      out.write("            -moz-opacity: 0.8; \r\n");
      out.write("            opacity:.80; \r\n");
      out.write("            filter: alpha(opacity=88); \r\n");
      out.write("        } \r\n");
      out.write("        .white_content { \r\n");
      out.write("            display: none; \r\n");
      out.write("            position: absolute; \r\n");
      out.write("            top: 25%; \r\n");
      out.write("            left: 25%; \r\n");
      out.write("            width: 55%; \r\n");
      out.write("            height: auto; \r\n");
      out.write("            padding: 20px; \r\n");
      out.write("            border: 10px solid orange; \r\n");
      out.write("            background-color: white; \r\n");
      out.write("            z-index:1002; \r\n");
      out.write("            overflow: auto; \r\n");
      out.write("        } \r\n");
      out.write("    </style>\r\n");
      out.write("<body style=\"background-color:#F8F8F8;min-width:1500px;\">\r\n");
      out.write("\t\t<!--顶部导航条1 -->\r\n");
      out.write("\t\t<div name=\"导航1\" style=\"width:auto;margin: 0 auto;background-color: #333;margin-top: 0px;margin-right: auto;margin-bottom: 0px;margin-left: auto;height: 32px;line-height: 32px;min-width:1500px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-l\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage\" style=\"color:#ddd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-logo\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t欢迎使用网上订餐网站！\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-r\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage login\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd login\" ><span id=\"username\" target=\"_top\" style=\"color:#ddd\"> </span></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t|\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage register\" style=\"color:#ddd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd register\"><a onclick=\"loginout()\" target=\"_top\" style=\"color:#ddd\">注销</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage home\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd\"><a href=\"#\" target=\"_top\" style=\"color:#ddd\">开店申请</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage my-shangcheng\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd MyShangcheng\"><a href=\"my.jsp\" target=\"_top\" style=\"color:#ddd\"><i class=\"am-icon-user am-icon-fw\"></i>个人中心</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage mini-cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd\"><a id=\"mc-menu-hd\" href=\"#\" target=\"_top\" style=\"color:#ddd\"><i class=\"am-icon-shopping-cart  am-icon-fw\"></i><span>购物车</span><strong id=\"J_MiniCartNum\" class=\"h\">0</strong></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"topMessage favorite\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-hd\"><a href=\"#\" target=\"_top\" style=\"color:#ddd\"><i class=\"am-icon-heart am-icon-fw\"></i><span>收藏夹</span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--顶部导航条2-->\r\n");
      out.write("\t\t<div name=\"导航2\" style=\"height:130px;width:auto;background:white\">\r\n");
      out.write("\t\t\t\t\t<!-- icon -->\r\n");
      out.write("\t\t\t\t\t<div style=\"margin:0px 0px 0px 0px;;vertical-align:middle; height:100px;width:300px;float:left\">\r\n");
      out.write("\t\t\t\t\t\t<div  style=\"height:80px;width:180px;float:left \">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"image/logo.JPG\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div   style=\"font-size:25px;margin-top:50px;font-weight:600;height:80px;vertical-align:middle; width:100px; float:left \">\r\n");
      out.write("\t\t\t\t\t\t\t 网上订餐\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--悬浮搜索框-->\r\n");
      out.write("\t\t\t\t\t<div style=\"float: right;  margin-top:40px;width: 290px;height: 38px; border: 1px solid #e5e5e5;\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"searchInput\" style=\"    float: left;display: block;width: 225px;height: 38px; ;font-size: 14px;color: #535353;border: none;background: none;margin-left:5px \" name=\"index_none_header_sysc\" type=\"text\" placeholder=\"搜索商家，美食\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"ai-topsearch\" class=\"submit am-btn\" style=\"height:38px;width:100px float: left \" value=\"搜索\" index=\"1\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 导航条2.1 -->\r\n");
      out.write("\t\t\t\t\t<div style=\"text-align:center; margin-left:auto; margin-right:auto; margin-top:5px;text-align:center;vertical-align:middle; height:100px;width:740px\">\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"home.jsp\" style=\"float:left;margin:40px;font-size:30px\">首页</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ddetail.jsp\" style=\"float:left;margin:40px;font-size:30px\">我的订单</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\"float:left;margin:40px;font-size:30px\">入驻加盟</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\"float:left;margin:40px;font-size:30px\">社会责任</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"clear \"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<!-- 跳转栏 -->\r\n");
      out.write("\t\t<div style=\" height:50px;width:1500px;margin-top:20px;    border-left: 10px solid #333;color: #444444;padding-left: 20px;margin-top: 20px;margin-right: auto;margin-bottom: 0px;margin-left: auto;\">\r\n");
      out.write("  \t\t\t<a href=\"foodlist.jsp\" style=\" font-size:30px;margin:20px\">商店名字</a>\r\n");
      out.write("  \t\t\t<i style=\" font-size:30px;margin:20px\">&gt;</i>\r\n");
      out.write("  \t\t\t<span style=\" font-size:30px;margin:20px;font-weight:600\">确认购买</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 结算页/信息页 -->\r\n");
      out.write("\t\t<div style=\" width:1500px;margin-top:20px;     color: #444444;padding-left: 20px;margin-top: 20px;margin-right: auto;margin-bottom: 0px;margin-left: auto;height:800px\">\r\n");
      out.write("\t\t\t<!-- 结算页 -->\r\n");
      out.write("\t\t\t<div style=\"margin-right:20px;background-color:white;border: 1px dotted  #ebebeb ;width:600px;float:left\">\r\n");
      out.write("\t\t\t\t<table style=\" font-size: 12px;border-collapse: collapse;width: 580px;color: #434343;border: 1px dotted  #ebebeb;background-color: #ffffff;margin:10px\">\r\n");
      out.write("          \t\t<tr>\r\n");
      out.write("          \t\t  <th width=\"240\" style=\"height:100px\"><div style=\"font-size:30px;margin:10px;font-weight:600;border-bottom: 1px dotted  #ebebeb\">菜品</div></th>\r\n");
      out.write("          \t\t  <th colspan=\"2\"><div style=\"font-size:30px;margin:10px;font-weight:600;border-bottom: 1px dotted  #ebebeb\">总价</div></th>\r\n");
      out.write("        \t    </tr>\r\n");
      out.write("          \t     </table >\r\n");
      out.write("          \t     <table  class=\"mytable\" style=\" font-size: 12px;border-collapse: collapse;width: 580px;color: #434343;border: 1px dotted  #ebebeb;background-color: #ffffff;margin:10px\">\r\n");
      out.write("          \t     \r\n");
      out.write("          \t     \r\n");
      out.write("           \t \t <tr>\r\n");
      out.write("               \t\t <td width=\"240\" style=\"height:100px\"> \r\n");
      out.write("                 \t\t <div  style=\"font-size:25px;margin:10px; border-bottom: 1px dotted  #ebebeb\">    \r\n");
      out.write("\t\t\t\t\t\t餐盒费\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                 \t\t\r\n");
      out.write("                \t</td>\r\n");
      out.write("                    <td  style=\"height:100px\">\r\n");
      out.write("                    \t<span style=\"font-size:25px;margin:10px; border-bottom: 1px dotted  #ebebeb;float:left\"> ¥ </span>\r\n");
      out.write("                    \t<div class=\"dep\"  style=\"font-size:25px;margin:10px; border-bottom: 1px dotted  #ebebeb\">\r\n");
      out.write("                    \t  2\r\n");
      out.write("                    \t</div>\r\n");
      out.write("                \t</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("               \t\t <td width=\"240\" style=\"height:100px\"> \r\n");
      out.write("                 \t\t <div  style=\"font-size:25px;margin:10px; border-bottom: 1px dotted  #ebebeb\">    \r\n");
      out.write("\t\t\t\t\t\t配送费\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                 \t\t\r\n");
      out.write("                \t</td>\r\n");
      out.write("                    <td  style=\"height:100px\">\r\n");
      out.write("                    \t<span style=\"font-size:25px;margin:10px; border-bottom: 1px dotted  #ebebeb;float:left\"> ¥ </span>\r\n");
      out.write("                    \t<div class=\"dep1\"  style=\"font-size:25px;margin:10px; border-bottom: 1px dotted  #ebebeb\">\r\n");
      out.write("                    \t  8\r\n");
      out.write("                    \t</div>\r\n");
      out.write("                \t</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("             \t <tr class=\"total\" data-total=\"80.8\">\r\n");
      out.write("             \t <td colspan=\"3\" style=\"height:80px\">\r\n");
      out.write("             \t   <div class=\"td-inner clearfix\" style=\"margin-right:50px;float:right\">\r\n");
      out.write("                \t  <span style=\"font-size:30px;margin:10px; border-bottom: 1px solid #ebebeb;font-weight:600\">合计</span>\r\n");
      out.write("                \t  <span style=\"font-size:30px;margin-right:10px; border-bottom: 1px solid #ebebeb;font-weight:600\"> ¥ </span>\r\n");
      out.write("                \t  <span class=\"tolprice\" style=\"font-size:30px;margin-right:10px; border-bottom: 1px solid #ebebeb;font-weight:600\"></span>\r\n");
      out.write("                   </div>\r\n");
      out.write("                 </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("     \r\n");
      out.write("      \t\t\t</table>\r\n");
      out.write("      \t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 信息页 -->\r\n");
      out.write("\t\t\t<div style=\"margin-left:20px;background-color:white;border: 1px solid #ebebeb;height:700px;width:820px;float:left\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-top:20px; width:820px;font-size:30px;text-align:center;font-weight:600; border-bottom: 1px dotted  #ebebeb\">\r\n");
      out.write("\t\t\t\t送餐详情\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\" font-size:25px;margin:10px \">\r\n");
      out.write("              \t 选择地址：\r\n");
      out.write("         \t\t </div>\r\n");
      out.write("       \t\t\t <!-- 弹出框 -->\r\n");
      out.write("       \t\t\t <div id=\"light\" class=\"white_content\" >\r\n");
      out.write("       \t\t\t \t<a style=\"width:100%;font-size:25px;text-align:right;float:right; margin :5px;color:#ebebeb\" href=\"javascript:void(0)\" onclick=\"document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none'\">关闭</a>\r\n");
      out.write("       \t\t\t \t<div style=\"height:100px;  width:100%;font-size:30px;text-align:center; margin :10px\">\r\n");
      out.write("       \t\t\t \t修改地址信息\r\n");
      out.write("       \t\t\t \t</div> \r\n");
      out.write("\t\t\t\t\t<div  style=\" text-align:center; margin :10px\">\r\n");
      out.write("\t\t\t\t\t\t<table style=\"margin-left:auto;margin-right:auto;   \">\r\n");
      out.write("\t\t\t\t\t\t<tbody><tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\" font-size:25px; margin :10px\">\r\n");
      out.write("\t\t\t\t\t\t收货人名字：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"dename\" style=\" font-size:25px; margin :10px\" type=\"text\" placeholder=\"输入收货人名称\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\" font-size:25px; margin :10px\">\r\n");
      out.write("\t\t\t\t\t\t收货人地址：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"deadd\" style=\" font-size:25px; margin :10px\" type=\"text\" placeholder=\"输入收货人地址\">\r\n");
      out.write("\t\t\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\" font-size:25px; margin :10px\">\r\n");
      out.write("\t\t\t\t\t\t收货人电话\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"detel\" style=\" font-size:25px; margin :10px\" type=\"text\" placeholder=\"输入收货人电话\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"am-btn am-btn-danger\"  style=\" font-size:25px; margin :10px\" >确认</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("        \t\t\t<div id=\"fade\" class=\"black_overlay\">\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t</div> \r\n");
      out.write("         \t\t <!--  地址样式 -->\r\n");
      out.write("\t\t\t\t<div class=\"am-avg-sm-1 am-avg-md-3 am-thumbnails\" style=\"height:130px\">\r\n");
      out.write("\t\t\t\t\t<li class=\"user-addresslist\" style=\"margin:5px;background:url('image/peraddbg.png') no-repeat;width:255px;height:150px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"new-option-r\" style=\"top:auto;margin-left:185px;position:relative\"><i class=\"am-icon-check-circle\"></i>默认地址</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"new-tit new-p-re\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span id=\"addr_name\" class=\"new-txt\" style=\"font-weight:600\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span id=\"addr_tel\" class=\"new-txt-rd2\" ></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"new-mu_l2a new-p-re\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"new-mu_l2cw\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\">地址：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"addr\" class=\"province\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"new-addr-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light').style.display='block';document.getElementById('fade').style.display='block'\"><i class=\"am-icon-edit\"></i>编辑</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"  width:820px;font-size:30px;text-align:center;font-weight:600; border-bottom: 1px dotted  #ebebeb\">\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"height:100px;  width:780px;font-size:25px;text-align:left; margin :20px ;border-bottom: 1px dotted  #ebebeb \">\r\n");
      out.write("\t\t\t\t给商家留言：\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"message\" placeholder=\"不要辣，多放盐等口味要求\" maxlength=\"100\" style=\"height:50px;width:600px;font-size:20px;float:right\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"height:150px ;margin-top:20px; width:780px;font-size:25px;text-align:left; margin:20px ;border-bottom: 1px dotted  #ebebeb\">\r\n");
      out.write("\t\t\t\t发票信息：\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"message2\" placeholder=\"请输入发票抬头\" maxlength=\"100\" style=\"height:50px;width:600px;font-size:20px;float:right\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div style=\"margin-top:50px\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"message3\" placeholder=\"请输入纳税人识别号\" maxlength=\"100\" style=\"height:50px;width:600px;font-size:20px;float:right\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"td-inner clearfix\" style=\"margin-left:50px;float:left;margin:20px;width:777px\">\r\n");
      out.write("                \t  <span style=\"font-size:30px;margin:10px; border-bottom: 1px solid #ebebeb;font-weight:600\">合计</span>\r\n");
      out.write("                \t  <span style=\"font-size:30px;margin-right:10px; border-bottom: 1px solid #ebebeb;font-weight:600\">¥ </span>\r\n");
      out.write("                 \t  <span class=\"tolprice\" style=\"font-size:30px;margin-right:10px; border-bottom: 1px solid #ebebeb;font-weight:600\"> </span>\r\n");
      out.write("                 \t  <span><a class=\"am-btn am-btn-danger\" style=\"font-size:25px;margin-left:10px;float:right\">取消</a></span>\r\n");
      out.write("                 \t  <span><a   onclick = \"Addorder()\" class=\"am-btn am-btn-danger\" style=\"font-size:25px; float:right\" >付款</a></span>\r\n");
      out.write("                 \t  \r\n");
      out.write("                 </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 脚注 -->\r\n");
      out.write("\t\t<div class=\"footer \" align=\"center\">\r\n");
      out.write("\t\t\t<div class=\"footer-hd \" >\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t<a href=\"# \"> </a>\r\n");
      out.write("\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t<a href=\"home.jsp\">商城首页</a>\r\n");
      out.write("\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t<a href=\"# \">支付宝</a>\r\n");
      out.write("\t\t\t\t<b>|</b>\r\n");
      out.write("\t\t\t\t<a href=\"# \">物流</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"footer-bd \" >\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t<a href=\"# \">关于我们</a>\r\n");
      out.write("\t\t\t\t<a href=\"# \">合作伙伴</a>\r\n");
      out.write("\t\t\t\t<a href=\"# \">联系我们</a>\r\n");
      out.write("\t\t\t\t<a href=\"# \">网站地图</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t\t//获取url传的值\r\n");
      out.write("\t\t\t\t\tvar sumlist = new Array();\r\n");
      out.write("\t\t\t\t\tvar sumlistp = new Array();\r\n");
      out.write("\t\t\t\t\tvar url = decodeURI(window.location.href);\r\n");
      out.write("\t\t\t\t\tconsole.log(url);\r\n");
      out.write("\t\t\t\t\tvar arr1 = url.split(\"?\")[1].split(\"&\");\r\n");
      out.write("\t\t\t\t\tvar temp = arr1[0].split(\"=\")[1].split(\" \");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar tempp = arr1[1].split(\"=\")[1].split(\" \");\r\n");
      out.write("\t\t\t\t\tfor(var i=0;i<temp.length;i++){\r\n");
      out.write("\t\t\t\t\t\tif(temp[i]!=\"\"){\r\n");
      out.write("\t\t\t\t\t\t\tsumlist[i] =temp[i];\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var i=0;i<tempp.length;i++){\r\n");
      out.write("\t\t\t\t\t\tif(tempp[i]!=\"\"){\r\n");
      out.write("\t\t\t\t\t\t\tsumlistp[i] =tempp[i];\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//处理sumlist、sumlistp、tolprice\r\n");
      out.write("\t\t\t\t\tfor(var i=0;i<sumlistp.length;i++){\r\n");
      out.write("\t\t\t\t\t\t//alert(sumlist[i]);\r\n");
      out.write("\t\t\t\t\t$(\".mytable\").prepend(\"<tr><td  width='240' style='height:100px'> <div class='left' style='font-size:25px;margin:10px; border-bottom: 1px dotted  #ebebeb'>    </div></td><td  style='height:100px'><span style='font-size:25px;margin:10px; border-bottom: 1px dotted  #ebebeb;float:left'> ¥ </span><div class='right' style='font-size:25px;margin:10px; border-bottom: 1px dotted  #ebebeb'></div></td></tr>\");\r\n");
      out.write("\t\t\t\t\t$(\".left\").eq(0).html(sumlist[i]);\r\n");
      out.write("\t\t\t\t\tconsole.log(sumlist[0]);\r\n");
      out.write("\t\t\t\t\t$(\".right\").eq(0).html(sumlistp[i]);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar tolprice = parseFloat(arr1[2].split(\"=\")[1])+parseFloat($(\".dep\").html())+parseFloat($(\".dep1\").html());\r\n");
      out.write("\t\t\t\t\t//alert(parseFloat(arr1[2].split(\"=\")[1])+parseFloat($(\".dep\").html()));\r\n");
      out.write("\t\t\t\t\t$(\".tolprice\").html(tolprice.toFixed(2));\r\n");
      out.write("\t\t\t\t\t$(\".new-option-r\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t$(this).parent('.user-addresslist').addClass(\"defaultAddr\").siblings().removeClass(\"defaultAddr\");\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar $ww = $(window).width();\r\n");
      out.write("\t\t\t\t\tif($ww>640) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#doc-modal-1\").removeClass(\"am-modal am-modal-no-btn\")\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t</script>\t\r\n");
      out.write("<script>\r\n");
      out.write("DisplayUsername();\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tDisplayUsername();\r\n");
      out.write("\tDisplayAddr();\r\n");
      out.write("});\r\n");
      out.write("function Addorder(){\r\n");
      out.write("\tvar userJsonStr = sessionStorage.getItem('user');\r\n");
      out.write("\tuserEntity = JSON.parse(userJsonStr);\r\n");
      out.write("\tvar username = userEntity.personalName ;\r\n");
      out.write("\tvar useraddr = userEntity.useraddr;\r\n");
      out.write("\tvar usertel = userEntity.usertel; \r\n");
      out.write("\tconsole.log(\"dasdas\");\r\n");
      out.write("\tvar sumlist = new Array();\r\n");
      out.write("\tvar sumlistp = new Array();\r\n");
      out.write("\tvar url = decodeURI(window.location.href);\r\n");
      out.write("\tvar arr1 = url.split(\"?\")[1].split(\"&\");\r\n");
      out.write("\tvar temp = arr1[0].split(\"=\")[1].split(\" \");\r\n");
      out.write("\tvar tempp = arr1[1].split(\"=\")[1].split(\" \");\r\n");
      out.write("\tfor(var i=0;i<temp.length;i++){\r\n");
      out.write("\t\tif(temp[i]!=\"\"&&tempp[i]!=\"\"){\r\n");
      out.write("\t\t\tsumlist[i] =temp[i];\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i=0;i<tempp.length;i++){\r\n");
      out.write("\t\tif(tempp[i]!=\"\"){\r\n");
      out.write("\t\t\tsumlistp[i] =tempp[i];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tvar tolprice = parseFloat(arr1[2].split(\"=\")[1])+parseFloat($(\".dep\").html())+parseFloat($(\".dep1\").html());\r\n");
      out.write("\tvar orderjson = {};\r\n");
      out.write("\tvar foodlist = [];\r\n");
      out.write("\tvar ordertime = new Date();\r\n");
      out.write("\torderjson.usertel = usertel;\r\n");
      out.write("\torderjson.useraddr = useraddr;\r\n");
      out.write("\torderjson.sumprice = tolprice;\r\n");
      out.write("\torderjson.ordertime = ordertime;\r\n");
      out.write("\torderjson.orderstatus = 0;\r\n");
      out.write("\tvar storeJsonStr = sessionStorage.getItem('store');\r\n");
      out.write("\tstoreEntity = JSON.parse(storeJsonStr);\r\n");
      out.write("\tconsole.log(storeEntity.storeid);\r\n");
      out.write("\torderjson.storeid = storeEntity.storeid;\r\n");
      out.write("\t\r\n");
      out.write("\tfor(i=0;i<sumlist.length;i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tvar food = {};\r\n");
      out.write("\t\tfood.foodname = sumlist[i];\r\n");
      out.write("\t\tfood.foodprice = sumlistp[i];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfood.selectNumber = 1;\r\n");
      out.write("\t\tfoodlist.push(food);\r\n");
      out.write("\t\t}\r\n");
      out.write("\torderjson.foodlist = foodlist;\r\n");
      out.write("\tconsole.log(orderjson)\r\n");
      out.write("\torderjson = JSON.stringify(orderjson);\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t url:\"CustomerAddOrderServlet\",\r\n");
      out.write("\t\t type:\"POST\",\r\n");
      out.write("\t\t data:orderjson,\r\n");
      out.write("\t\t datatype:\"json\",\r\n");
      out.write("\t\t success:function(data){\r\n");
      out.write("\t\t\t if(data.code == 200)\r\n");
      out.write("\t\t\t\t {\r\n");
      out.write("\t\t\t\t alert(data.message)\r\n");
      out.write("\t\t\t\t $(location).attr('href', '/OrderTakeOutFood/erweima.jsp');\r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("\t\t\t else{\r\n");
      out.write("\t\t\t\t alert(data.message)\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t }\r\n");
      out.write("\t})\r\n");
      out.write("};\r\n");
      out.write("function DisplayAddr(){\r\n");
      out.write("\tvar userJsonStr = sessionStorage.getItem('user');\r\n");
      out.write("\tuserEntity = JSON.parse(userJsonStr);\r\n");
      out.write("\tvar username = userEntity.personalName ;\r\n");
      out.write("\tvar useraddr = userEntity.useraddr;\r\n");
      out.write("\tvar usertel = userEntity.usertel;\r\n");
      out.write("\t$(\"#addr_name\").html(username);\r\n");
      out.write("\t$(\"#addr_tel\").html(useraddr);\r\n");
      out.write("\t$(\"#addr\").html(usertel);\r\n");
      out.write("};\r\n");
      out.write("function DisplayUsername(){\r\n");
      out.write("\tvar userJsonStr = sessionStorage.getItem('user');\r\n");
      out.write("\tuserEntity = JSON.parse(userJsonStr);\r\n");
      out.write("\tvar username = userEntity.username ;\r\n");
      out.write("\t$(\"#username\").html(username);\r\n");
      out.write("};\r\n");
      out.write("function loginout(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\turl:\"CustomerLoginOutServlet\",\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tdatatype:\"json\",\r\n");
      out.write("\t\tsuccess: function (data)  \r\n");
      out.write("        {  \r\n");
      out.write("      \t\r\n");
      out.write("     \t   if(data.code == 200)\r\n");
      out.write("     \t   {\r\n");
      out.write("     \t\t  sessionStorage.removeItem('user');\r\n");
      out.write("     \t\t$(location).attr('href', '/OrderTakeOutFood/login.jsp');\r\n");
      out.write("     \t   \talert(data.message)\r\n");
      out.write("     \t   \t\t\r\n");
      out.write("     \t   }else{\r\n");
      out.write("     \t\t   alert(data.message);\r\n");
      out.write("     \t   }\t\t   \t            \t\r\n");
      out.write("          },\r\n");
      out.write("        error: function()\r\n");
      out.write("        {\r\n");
      out.write("      \t  console.log(\"提交错误\")\r\n");
      out.write("        }\r\n");
      out.write("\t})\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
